[INFO] Loaded bot token: 7366166182...
ðŸ¤– Bot is running. Saving links to: /home/sagar/Documents/automater/data/fetched_links.txt
[INFO] Logging into Instagram as trianga_tapes...
Loaded session from /home/sagar/.config/instaloader/session-trianga_tapes.
[INFO] Session loaded successfully.
[INFO] Categorized as movies: https://www.instagram.com/reel/DGTN0MspRzl/?igsh=bGM1ZmJnMjR0d2k=
[INFO] Categorized as cars: https://www.instagram.com/reel/DE5B3tOCUN9/?igsh=MW5ubHJ6MzJxc2doeA==
[INFO] Categorized as anime: https://www.instagram.com/reel/DKnzkcCqIBY/?igsh=bmxqZXBnc2R4c3M4
[INFO] Categorized as anime: https://www.instagram.com/reel/DGkny1yvaEP/?igsh=MWlvdzRpeW9hcXp6bQ==
[INFO] Categorized as edits: https://www.instagram.com/reel/DH1POsuvcXW/?igsh=N3YyN2I0MTZscGp1
[INFO] Categorized as anime: https://www.instagram.com/reel/DEz7L6tKMMU/?igsh=MXAxNndtNGE0NjF3bg==
Traceback (most recent call last):
  File "/home/sagar/Documents/automater/scripts/metadata_collector.py", line 71, in <module>
    main()
    ~~~~^^
  File "/home/sagar/Documents/automater/scripts/metadata_collector.py", line 58, in main
    post = instaloader.Post.from_shortcode(L.context, shortcode)
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/instaloader/structures.py", line 207, in from_shortcode
    post._node = post._full_metadata
                 ^^^^^^^^^^^^^^^^^^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/instaloader/structures.py", line 345, in _full_metadata
    self._obtain_metadata()
    ~~~~~~~~~~~~~~~~~~~~~^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/instaloader/structures.py", line 322, in _obtain_metadata
    pic_json = self._context.doc_id_graphql_query(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        "8845758582119845", {"shortcode": self.shortcode}
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )["data"]["xdt_shortcode_media"]
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/instaloader/instaloadercontext.py", line 543, in doc_id_graphql_query
    resp_json = self.get_json('graphql/query',
                              params={'variables': variables_json,
    ...<2 lines>...
                              session=tmpsession,
                              use_post=True)
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/instaloader/instaloadercontext.py", line 411, in get_json
    self.do_sleep()
    ~~~~~~~~~~~~~^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/instaloader/instaloadercontext.py", line 367, in do_sleep
    time.sleep(min(random.expovariate(0.6), 15.0))
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
ðŸ¤– Bot running. Saving links to: /home/sagar/Documents/automater/data/fetched_links.txt
[INFO] Logging into Instagram as trianga_tapes...
Loaded session from /home/sagar/.config/instaloader/session-trianga_tapes.
[INFO] Session loaded successfully.
[INFO] Categorized as movies: https://www.instagram.com/reel/DGTN0MspRzl/?igsh=bGM1ZmJnMjR0d2k=
[INFO] Categorized as cars: https://www.instagram.com/reel/DE5B3tOCUN9/?igsh=MW5ubHJ6MzJxc2doeA==
[INFO] Categorized as anime: https://www.instagram.com/reel/DKnzkcCqIBY/?igsh=bmxqZXBnc2R4c3M4
[INFO] Categorized as anime: https://www.instagram.com/reel/DGkny1yvaEP/?igsh=MWlvdzRpeW9hcXp6bQ==
[INFO] Categorized as edits: https://www.instagram.com/reel/DH1POsuvcXW/?igsh=N3YyN2I0MTZscGp1
[INFO] Categorized as anime: https://www.instagram.com/reel/DEz7L6tKMMU/?igsh=MXAxNndtNGE0NjF3bg==
[INFO] Categorized as anime: https://www.instagram.com/reel/DG6lFQWtVlt/?igsh=YTk2MHU1OXB0NTV6
[INFO] Categorized as cars: https://www.instagram.com/reel/DKTuXEHz5_Q/?igsh=MTh5eGF2d2FlcGp5NQ==
[INFO] Categorized as edits: https://www.instagram.com/reel/DIHE0GgPVcu/?igsh=NHY0aXBlaTMwYWx5
[INFO] Categorized as cars: https://www.instagram.com/reel/DI3clc3i7Fz/?igsh=bDJpb3Z6d3I4a2Rv
[INFO] Categorized as anime: https://www.instagram.com/reel/DITy8iWpoAo/?igsh=MTdlbG0yN2lnZjZjZw==
[INFO] Categorized as anime: https://www.instagram.com/reel/DFLg1cXMU4X/?igsh=cWY5cmpoZHZ0dnVs
[INFO] Categorized as anime: https://www.instagram.com/reel/DIt-NAwMhyU/?igsh=ZDZrbGNkYWljZmZj
[INFO] Categorized as cars: https://www.instagram.com/reel/DFdfJHOMu4n/?igsh=NXJrNnFvaGY1a2Jy
[INFO] Categorized as uncategorized: https://www.instagram.com/reel/DKocgonzxeg/?igsh=MW9zbXB5cXdrbWxjbA==
[INFO] Categorized as edits: https://www.instagram.com/reel/DKWAoveSsmP/?igsh=MW84Z2l4aWlld2JpZA==
[INFO] Categorized as edits: https://www.instagram.com/reel/DKWAoveSsmP/?igsh=MW84Z2l4aWlld2JpZA==
[INFO] Categorized as uncategorized: https://www.instagram.com/reel/DKpBymQzPI_/?igsh=MXFrbjVua2hpYmxwdw==
[INFO] Categorized as uncategorized: https://www.instagram.com/reel/DKpBymQzPI_/?igsh=MXFrbjVua2hpYmxwdw==
[INFO] Categorized as anime: https://www.instagram.com/reel/DITy8iWpoAo/?igsh=MTdlbG0yN2lnZjZjZw==
[INFO] Categorized as cars: https://www.instagram.com/reel/DI3clc3i7Fz/?igsh=bDJpb3Z6d3I4a2Rv
ðŸ¤– Bot running. Saving links to: /home/sagar/Documents/automater/data/fetched_links.txt
Traceback (most recent call last):
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/anyio/_core/_tasks.py", line 115, in fail_after
    yield cancel_scope
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/anyio/_core/_sockets.py", line 208, in connect_tcp
    gai_res = await getaddrinfo(
              ^^^^^^^^^^^^^^^^^^
        target_host, remote_port, family=family, type=socket.SOCK_STREAM
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/anyio/_core/_sockets.py", line 584, in getaddrinfo
    gai_res = await get_async_backend().getaddrinfo(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        encoded_host, port, family=family, type=type, proto=proto, flags=flags
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/anyio/_backends/_asyncio.py", line 2692, in getaddrinfo
    return await get_running_loop().getaddrinfo(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        host, port, family=family, type=type, proto=proto, flags=flags
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/asyncio/base_events.py", line 933, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        None, getaddr_func, host, port, family, type, proto, flags)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Cancelled by cancel scope b60f1228

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
    yield
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpcore/_backends/anyio.py", line 113, in connect_tcp
    with anyio.fail_after(timeout):
         ~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/anyio/_core/_tasks.py", line 118, in fail_after
    raise TimeoutError
TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 262, in handle_async_request
    raise exc
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpcore/_async/connection.py", line 92, in handle_async_request
    raise exc
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpcore/_async/connection.py", line 69, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpcore/_async/connection.py", line 117, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpcore/_backends/auto.py", line 31, in connect_tcp
    return await self._backend.connect_tcp(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpcore/_backends/anyio.py", line 112, in connect_tcp
    with map_exceptions(exc_map):
         ~~~~~~~~~~~~~~^^^^^^^^^
  File "/usr/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/request/_httpxrequest.py", line 216, in do_request
    res = await self._client.request(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
    )
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
         ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sagar/Documents/automater/scripts/link_fitcher.py", line 48, in <module>
    app.run_polling()
    ~~~~~~~~~~~~~~~^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/ext/_application.py", line 727, in run_polling
    return self.__run(
           ~~~~~~~~~~^
        updater_coroutine=self.updater.start_polling(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<12 lines>...
        stop_signals=stop_signals,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/ext/_application.py", line 921, in __run
    raise exc
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/ext/_application.py", line 910, in __run
    loop.run_until_complete(self.initialize())
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/asyncio/base_events.py", line 719, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/ext/_application.py", line 399, in initialize
    await self.bot.initialize()
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 271, in initialize
    await super().initialize()
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/_bot.py", line 591, in initialize
    await self.get_me()
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 1706, in get_me
    return await super().get_me(
           ^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/_bot.py", line 381, in decorator
    result = await func(self, *args, **kwargs)  # skipcq: PYL-E1102
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/_bot.py", line 736, in get_me
    result = await self._post(
             ^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/_bot.py", line 469, in _post
    return await self._do_post(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/ext/_extbot.py", line 325, in _do_post
    return await super()._do_post(
           ^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/_bot.py", line 497, in _do_post
    return await request.post(
           ^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 168, in post
    result = await self._request_wrapper(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 291, in _request_wrapper
    raise exc
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/request/_baserequest.py", line 277, in _request_wrapper
    code, payload = await self.do_request(
                    ^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/home/sagar/Documents/hacking-/venv/lib/python3.13/site-packages/telegram/request/_httpxrequest.py", line 233, in do_request
    raise TimedOut from err
telegram.error.TimedOut: Timed out
[INFO] Logging into Instagram as trianga_tapes...
Loaded session from /home/sagar/.config/instaloader/session-trianga_tapes.
[INFO] Session loaded successfully.
[INFO] Categorized as movies: https://www.instagram.com/reel/DGTN0MspRzl/?igsh=bGM1ZmJnMjR0d2k=
[INFO] Categorized as cars: https://www.instagram.com/reel/DE5B3tOCUN9/?igsh=MW5ubHJ6MzJxc2doeA==
[INFO] Categorized as anime: https://www.instagram.com/reel/DKnzkcCqIBY/?igsh=bmxqZXBnc2R4c3M4
[INFO] Categorized as anime: https://www.instagram.com/reel/DGkny1yvaEP/?igsh=MWlvdzRpeW9hcXp6bQ==
[INFO] Categorized as edits: https://www.instagram.com/reel/DH1POsuvcXW/?igsh=N3YyN2I0MTZscGp1
[INFO] Categorized as anime: https://www.instagram.com/reel/DEz7L6tKMMU/?igsh=MXAxNndtNGE0NjF3bg==
[INFO] Categorized as anime: https://www.instagram.com/reel/DG6lFQWtVlt/?igsh=YTk2MHU1OXB0NTV6
[INFO] Categorized as cars: https://www.instagram.com/reel/DKTuXEHz5_Q/?igsh=MTh5eGF2d2FlcGp5NQ==
[INFO] Categorized as edits: https://www.instagram.com/reel/DIHE0GgPVcu/?igsh=NHY0aXBlaTMwYWx5
[INFO] Categorized as cars: https://www.instagram.com/reel/DI3clc3i7Fz/?igsh=bDJpb3Z6d3I4a2Rv
[INFO] Categorized as anime: https://www.instagram.com/reel/DITy8iWpoAo/?igsh=MTdlbG0yN2lnZjZjZw==
[INFO] Categorized as anime: https://www.instagram.com/reel/DFLg1cXMU4X/?igsh=cWY5cmpoZHZ0dnVs
[INFO] Categorized as anime: https://www.instagram.com/reel/DIt-NAwMhyU/?igsh=ZDZrbGNkYWljZmZj
[INFO] Categorized as cars: https://www.instagram.com/reel/DFdfJHOMu4n/?igsh=NXJrNnFvaGY1a2Jy
[INFO] Categorized as uncategorized: https://www.instagram.com/reel/DKocgonzxeg/?igsh=MW9zbXB5cXdrbWxjbA==
[INFO] Categorized as edits: https://www.instagram.com/reel/DKWAoveSsmP/?igsh=MW84Z2l4aWlld2JpZA==
[INFO] Categorized as edits: https://www.instagram.com/reel/DKWAoveSsmP/?igsh=MW84Z2l4aWlld2JpZA==
[INFO] Categorized as uncategorized: https://www.instagram.com/reel/DKpBymQzPI_/?igsh=MXFrbjVua2hpYmxwdw==
[INFO] Categorized as uncategorized: https://www.instagram.com/reel/DKpBymQzPI_/?igsh=MXFrbjVua2hpYmxwdw==
[INFO] Categorized as anime: https://www.instagram.com/reel/DITy8iWpoAo/?igsh=MTdlbG0yN2lnZjZjZw==
[INFO] Categorized as cars: https://www.instagram.com/reel/DI3clc3i7Fz/?igsh=bDJpb3Z6d3I4a2Rv
